---
name: "Comic Vine"
guid: "309ec7e5-4981-4e8c-992f-8e4dde9591e0"
version: 1
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Comic Vine Metadata Provider"
description: >
  Supports several different metadata providers and options for organizing your collection.
category: "Books"
artifacts:
  - "Jellyfin.Plugin.ComicVine.dll"
changelog: |-
  - Fix nullability for 10.10 (#116) @crobibero
  - Update opf and add ISBN (#108) @AshleyDeo
  - Add Comic Vine Person provider (#85) @Pithaya

  ### New features and improvements ###
  - Add support for covers from .cbt, .cb7 and .cbr (#112) @oddstr13

  ### Dependency updates ###
  - Update dependency Microsoft.NET.Test.Sdk to 17.11.1 (#106) @renovate
  - Update xunit-dotnet monorepo (#84) @renovate
  - Update dependency Microsoft.Extensions.Http to 8.0.1 - autoclosed (#115) @renovate
